on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: g++ -std=c++20 -Wall -Wextra -Werror -Wpedantic *.cpp

  clang-format:
    runs-on: ubuntu-latest
    container: ghcr.io/cpp-linter/clang-tools:18
    steps:
    - uses: actions/checkout@v4
    - run: find . -iname "*.hpp" -o -iname "*.h" | xargs clang-format --dry-run -Werror *.cpp

  clang-tidy:
    runs-on: ubuntu-latest
    container: ghcr.io/cpp-linter/clang-tools:18
    steps:
    - uses: actions/checkout@v4
    - run: clang-tidy *.cpp
